name: churn_imbalanced
on: [push]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: iterative/setup-cml@v1

      - name: Upgrade pip and install compatible dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.23.5 scikit-learn==1.3.2 Cython==3.0.2

      - name: Prepare Environment
        run: |
          pip install -r requirements.txt
          python Script.py

      - name: Generate Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" > report.md
          awk 'NR%4{print"      "$0}{print""}' metrix.txt >> report.md
          echo "\n## Confusion Matrix" >> report.md
          echo "![](confusion_matrix.png)" >> report.md
          cml comment create report.md